# Configmaps for envoy one for each network node
# This will change, we plan to only have envoy for a network node only if specified in the config
{{- range $index, $node := ($.Values.hedera.nodes) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-proxy-cm-{{ $node.name }}
  namespace: {{ default $.Release.Namespace $.Values.global.namespaceOverride }}
  labels:
    {{- include "solo.testLabels" $ | nindent 4 }}
data:
  {{- if (lookup "v1" "Secret" (default $.Release.Namespace $.Values.global.namespaceOverride) (printf "envoy-proxy-secret-%s" $node.name)) }}
    # Include TLS configuration since secret exists
  envoy.yaml: |
  {{- tpl ($.Files.Get "config-files/envoy-with-tls.yaml") (dict "nodeConfig" $node "Template" $.Template) | nindent 4 }}

  {{- else }}
    # Default non-TLS configuration if the secret does not exist
  envoy.yaml: |
    {{- tpl ($.Files.Get "config-files/envoy.yaml") (dict "nodeConfig" $node "Template" $.Template) | nindent 4 }}
  {{- end }}
---
{{ end }}
