# Create a haproxy configmap for each network node
# This will change in the future, we plan create a haproxy for a given network node only if specified in the config
{{- range $index, $node := ($.Values.hedera.nodes) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-cm-{{ $node.name }}
  namespace: {{ default $.Release.Namespace $.Values.global.namespaceOverride }}
  labels:
    {{- include "solo.testLabels" $ | nindent 4 }}
data:
  {{- if (lookup "v1" "Secret" (default $.Release.Namespace $.Values.global.namespaceOverride) (printf "haproxy-proxy-secret-%s" $node.name)) }}
  # Include TLS configuration since secret exists
  haproxy.cfg: |
    {{- tpl ($.Files.Get "config-files/haproxy-with-tls.cfg") (dict "nodeConfig" $node "namespace" $.Release.Namespace "Template" $.Template) | nindent 4 }}

  {{- else }}
  # Default non-TLS configuration if the secret does not exist
  haproxy.cfg: |
    {{- tpl ($.Files.Get "config-files/haproxy.cfg") (dict "nodeConfig" $node "namespace" $.Release.Namespace "Template" $.Template) | nindent 4 }}
  {{- end }}

---

{{ end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-ofac-cm
data:
  ofacBlock.acl: |
    {{- .Files.Get "config-files/ofacBlock.acl" | nindent 4  }}
