{{- if $.Values.defaults.sidecars.backupUploader.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: rclone-config
  namespace: {{ default $.Release.Namespace $.Values.global.namespaceOverride }}
data:
  rclone.conf: |-
    [backups]
    type = ${RCLONE_CONFIG_BACKUPS_TYPE}
    provider = ${RCLONE_CONFIG_BACKUPS_PROVIDER}
    env_auth = true
    region = ${RCLONE_CONFIG_BACKUPS_REGION}
    endpoint = ${RCLONE_CONFIG_BACKUPS_ENDPOINT}
{{- end}}
