receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
  # Add standard label sets to both logs and metrics.
  attributes/addLabels:
    actions:
      - key: environment
        action: insert
        value: "{{ .environment_name }}"
      - key: metrics_node_id
        action: insert
        value: "{{ .otel_node_id | add1 }}"
      - key: node_id
        action: insert
        value: "{{ .otel_node_id }}"
      # TODO how to pass otel_instance_hostname and otel_instance_ip?
      #      - key: inventory_name
      #        action: insert
      #        value: "{{ .otel_instance_hostname }} - {{ .otel_instance_ip }}"
      - key: instance_type
        action: insert
        value: "{{ .otel_instance_type }}"

exporters:
  prometheus:
    endpoint: "0.0.0.0:9090" # note: network-node service exposes this port for all prometheus metrics instead of node's port 9999
    const_labels:
      source: p-{{ default "otel-collector" .otelDefaults.nameOverride }} # PromQL: {source="p-otel-collector"}

  otlp:
    endpoint: "{{ .otelDefaults.exporters.otlp.endpoint }}"
    tls:
      {{- .otelDefaults.exporters.otlp.tls | toYaml | nindent 6 }}

extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    metrics:
      receivers:
        - prometheus
      processors:
        - attributes/addLabels
        - batch
      exporters:
        - prometheus
