{{- if $.Values.deployment.podDisruptionBudget.create }}
{{ range $index, $node := $.Values.hedera.nodes }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: network-node-pdb-{{ $node.name }}
  namespace: {{ default $.Release.Namespace $.Values.global.namespaceOverride }}
  labels:
    solo.hedera.com/type: pod-disruption-budget
    solo.hedera.com/node-name: {{ $node.name }}
spec:
  selector:
    matchLabels:
      solo.hedera.com/type: network-node
      solo.hedera.com/node-name: {{ $node.name }}
  {{- if $.Values.deployment.podDisruptionBudget.minAvailable }}
  minAvailable: {{ $.Values.deployment.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if $.Values.deployment.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ $.Values.deployment.podDisruptionBudget.maxUnavailable }}
  {{- end }}
{{- end }}
{{- end }}
