{{- if not $.Values.defaults.sidecars.backupUploader.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: backup-uploader-secrets
  namespace: {{ default $.Release.Namespace $.Values.global.namespaceOverride }}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  RCLONE_CONFIG_BACKUPS_ENDPOINT: ""
  RCLONE_CONFIG_BACKUPS_REGION: ""
  RCLONE_CONFIG_BACKUPS_TYPE: "s3"
  RCLONE_CONFIG_BACKUPS_PROVIDER: "GCS"
{{- end}}
