{{- if not $.Values.defaults.sidecars.backupUploader.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: backup-uploader-secrets
  namespace: {{ default $.Release.Namespace $.Values.global.namespaceOverride }}
type: Opaque
data:
  S3_ACCESS_KEY: ""
  S3_SECRET_KEY: ""
  S3_ENDPOINT: ""
  S3_REGION: ""
  RCLONE_TYPE: ""
  RCLONE_CONFIG_BACKUPS_PROVIDER: ""
{{- end}}
