apiVersion: v1
kind: Secret
metadata:
  name: backup-uploader-secrets
  namespace: {{ default $.Release.Namespace $.Values.global.namespaceOverride }}
type: Opaque
data:
  S3_ACCESS_KEY: {{ coalesce (.Values.cloud.s3.S3_ACCESS_KEY | b64enc) }}
  S3_SECRET_KEY: {{ coalesce (.Values.cloud.s3.S3_SECRET_KEY | b64enc) }}
  GCS_ACCESS_KEY: {{ coalesce (.Values.cloud.gcs.GCS_ACCESS_KEY | b64enc) }}
  GCS_SECRET_KEY: {{ coalesce (.Values.cloud.gcs.GCS_SECRET_KEY | b64enc) }}
