{{- $previous := lookup "v1" "Secret" .Release.Namespace "uploader-mirror-secrets" }}
{{- $minio_accessKey := randAlpha 10  -}}
{{- $minio_secretKey := randAlpha 10  -}}
{{- $minio_url := printf "http://%s-hl:9000" (index $.Values "minio-server" "tenant" "name") -}}
{{- if .Values.cloud.generateNewSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: minio-secrets
  namespace: {{ default $.Release.Namespace $.Values.global.namespaceOverride }}
type: Opaque
data:
  {{- if and ((($previous).data).S3_ACCESS_KEY) ((($previous).data).S3_SECRET_KEY)}}
  config.env: {{ printf "export MINIO_ROOT_USER=%s\nexport MINIO_ROOT_PASSWORD=%s" ((($previous).data).S3_ACCESS_KEY | b64dec)  ((($previous).data).S3_SECRET_KEY | b64dec) | b64enc -}}
  {{- else }}
  config.env: {{ printf "export MINIO_ROOT_USER=%s\nexport MINIO_ROOT_PASSWORD=%s" ($minio_accessKey) ($minio_secretKey) | b64enc }}
  {{- end }}
{{- end }}
---
{{- if .Values.cloud.generateNewSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: uploader-mirror-secrets
type: Opaque
data:
  S3_ACCESS_KEY: {{ coalesce ((($previous).data).S3_ACCESS_KEY) ($minio_accessKey | b64enc) }}
  S3_SECRET_KEY: {{ coalesce ((($previous).data).S3_SECRET_KEY) ($minio_secretKey | b64enc) }}
  # The below keys will be ignored by the uploader side cars
  # These will be used by mirror importer to download stream files, storage source could be minio or cloud storage
  HEDERA_MIRROR_IMPORTER_DOWNLOADER_SOURCES_0_TYPE: {{ "S3" | b64enc }}
  HEDERA_MIRROR_IMPORTER_DOWNLOADER_SOURCES_0_URI: {{ $minio_url |b64enc }}
  HEDERA_MIRROR_IMPORTER_DOWNLOADER_SOURCES_0_CREDENTIALS_ACCESSKEY: {{ coalesce ((($previous).data).S3_ACCESS_KEY) ($minio_accessKey | b64enc) }}
  HEDERA_MIRROR_IMPORTER_DOWNLOADER_SOURCES_0_CREDENTIALS_SECRETKEY: {{ coalesce ((($previous).data).S3_SECRET_KEY) ($minio_secretKey | b64enc) }}
{{- end }}
---
