{{- $previous := lookup "v1" "Secret" .Release.Namespace "uploader-mirror-secrets" }}
{{- $minio_accessKey := randAlpha 10  -}}
{{- $minio_secretKey := randAlpha 10  -}}
{{- $minio_config_env := printf "export MINIO_ROOT_USER=%s\nexport MINIO_ROOT_PASSWORD=%s" (coalesce ((($previous).data).S3_ACCESS_KEY) $minio_accessKey) (coalesce ((($previous).data).S3_SECRET_KEY) $minio_secretKey) -}}
{{- $minio_url := printf "http://%s-hl:9000" (index $.Values "minio-server" "tenant" "name") -}}
apiVersion: v1
kind: Secret
metadata:
  name: minio-secrets
  namespace: {{ default $.Release.Namespace $.Values.global.namespaceOverride }}
type: Opaque
data:
  config.env: {{ $minio_config_env | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: uploader-mirror-secrets
type: Opaque
data:
  S3_ACCESS_KEY: {{ coalesce (.Values.cloud.s3.S3_ACCESS_KEY | b64enc) ((($previous).data).S3_ACCESS_KEY) ($minio_accessKey | b64enc) }}
  S3_SECRET_KEY: {{ coalesce (.Values.cloud.s3.S3_SECRET_KEY | b64enc) ((($previous).data).S3_SECRET_KEY) ($minio_secretKey | b64enc) }}
  GCS_ACCESS_KEY: {{ coalesce (.Values.cloud.gcs.GCS_ACCESS_KEY | b64enc) ((($previous).data).GCS_ACCESS_KEY) ($minio_accessKey | b64enc) }}
  GCS_SECRET_KEY: {{ coalesce (.Values.cloud.gcs.GCS_SECRET_KEY | b64enc) ((($previous).data).GCS_SECRET_KEY) ($minio_secretKey | b64enc) }}
  # The below keys will be ignored by the uploader side cars
  # These will be used by mirror node to connect to minio
  {{- if .Values.cloud.gcs.enabled }}
  HEDERA_MIRROR_IMPORTER_DOWNLOADER_SOURCES_0_TYPE: {{ "GCP" | b64enc }}
  HEDERA_MIRROR_IMPORTER_DOWNLOADER_SOURCES_0_URI: {{ .Values.cloud.gcs.endpoint |b64enc }}
  HEDERA_MIRROR_IMPORTER_DOWNLOADER_SOURCES_0_CREDENTIALS_ACCESSKEY: {{ .Values.cloud.gcs.GCS_ACCESS_KEY | b64enc }}
  HEDERA_MIRROR_IMPORTER_DOWNLOADER_SOURCES_0_CREDENTIALS_SECRETKEY: {{ .Values.cloud.gcs.GCS_SECRET_KEY | b64enc }}
  {{- end}}
  {{- if .Values.cloud.s3.enabled }}
  HEDERA_MIRROR_IMPORTER_DOWNLOADER_SOURCES_0_TYPE: {{ "S3" | b64enc }}
  HEDERA_MIRROR_IMPORTER_DOWNLOADER_SOURCES_0_URI: {{ .Values.cloud.s3.endpoint |b64enc }}
  HEDERA_MIRROR_IMPORTER_DOWNLOADER_SOURCES_0_CREDENTIALS_ACCESSKEY: {{ .Values.cloud.s3.S3_ACCESS_KEY | b64enc }}
  HEDERA_MIRROR_IMPORTER_DOWNLOADER_SOURCES_0_CREDENTIALS_SECRETKEY: {{ .Values.cloud.s3.S3_SECRET_KEY | b64enc }}
  {{- else if .Values.cloud.minio.enabled }}
  HEDERA_MIRROR_IMPORTER_DOWNLOADER_SOURCES_0_TYPE: {{ "S3" | b64enc }}
  HEDERA_MIRROR_IMPORTER_DOWNLOADER_SOURCES_0_URI: {{ $minio_url |b64enc }}
  HEDERA_MIRROR_IMPORTER_DOWNLOADER_SOURCES_0_CREDENTIALS_ACCESSKEY: {{ ($minio_accessKey | b64enc) }}
  HEDERA_MIRROR_IMPORTER_DOWNLOADER_SOURCES_0_CREDENTIALS_SECRETKEY: {{ ($minio_secretKey | b64enc) }}
  {{- end }}
---
