apiVersion: v1
entries:
  solo-cluster-setup:
  - apiVersion: v2
    appVersion: 0.32.0
    created: "2024-10-04T14:54:59.473337047Z"
    dependencies:
    - alias: minio-operator
      condition: cloud.minio.enabled
      name: operator
      repository: https://operator.min.io/
      version: 5.0.7
    - alias: prometheus-stack
      condition: cloud.prometheusStack.enabled
      name: kube-prometheus-stack
      repository: https://prometheus-community.github.io/helm-charts
      version: 52.0.1
    - condition: cloud.grafanaAgent.enabled
      name: grafana-agent
      repository: https://grafana.github.io/helm-charts
      version: 0.27.1
    - condition: cloud.certManager.enabled
      name: cert-manager
      repository: https://charts.jetstack.io
      version: v1.13.3
    description: An umbrella Helm chart to setup shared resources for 1+ deployments
      of the `solo-deployment` chart(s)
    digest: a9c5edd63d220d8582454eb2decf520908308753c3c2c0934651127c2fe423b3
    name: solo-cluster-setup
    type: application
    urls:
    - https://hashgraph.github.io/solo-charts/charts/solo-cluster-setup-0.32.0.tgz
    version: 0.32.0
  solo-deployment:
  - apiVersion: v2
    appVersion: 0.32.0
    created: "2024-10-04T14:54:59.502454594Z"
    dependencies:
    - condition: hedera-explorer.enabled
      name: hedera-explorer
      repository: ""
      version: 0.2.0
    - alias: hedera-mirror-node
      condition: hedera-mirror-node.enabled
      name: hedera-mirror
      repository: https://hashgraph.github.io/hedera-mirror-node/charts
      version: 0.113.0
    - alias: minio-server
      condition: cloud.minio.enabled
      name: tenant
      repository: https://operator.min.io/
      version: 5.0.12
    - condition: cloud.acmeClusterIssuer.enabled
      name: acme-cluster-issuer
      repository: https://swirldslabs.github.io/swirldslabs-helm-charts
      version: 0.3.1
    - condition: cloud.haproxyIngressController.enabled
      name: haproxy-ingress
      repository: https://haproxy-ingress.github.io/charts
      version: 0.14.5
    description: An umbrella Helm chart for a chart deployment of `solo-deployment`
    digest: 53367241847c91b4436237d5193dc657a5648bba4560b686c224475359006e69
    kubeVersion: '>=1.25.0-0'
    name: solo-deployment
    type: application
    urls:
    - https://hashgraph.github.io/solo-charts/charts/solo-deployment-0.32.0.tgz
    version: 0.32.0
generated: "2024-10-04T14:54:59.442233947Z"
