kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: solo # this is overridden if CLUSTER_NAME env var is set. Check .env file
nodes:
  - role: control-plane
    labels:
      solo-scheduling.io/role: network