{{- if $.Values.explorerIngressController.enabled }}
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: {{ .Values.explorerIngressController.explorerIngressClass }}
spec:
  controller: haproxy-ingress.github.io/controller
{{- end }}
