{{- if $.Values.mirrorIngressController.enabled }}
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: {{ .Values.mirrorIngressController.mirrorIngressClassName }}
spec:
  controller: haproxy-ingress.github.io/controller
{{- end }}
