apiVersion: v2
name: haproxy-ingress
description: HAProxy Ingress Controller for Kubernetes
type: application
version: 0.14.5
appVersion: 1.0
keywords:
  - ingress
  - haproxy
sources:
  - https://github.com/haproxy-ingress/haproxy-ingress