# SPDX-License-Identifier: Apache-2.0

{{ if .Values.postgresql.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels: {{- include "solo-shared-resources.labels" . | nindent 4 }}
  name: {{ .Release.Name }}-init
  namespace: {{ include "solo-shared-resources.namespace" . }}
{{- end }}
