{{ range $index, $node := ($.Values.hedera.nodes) }}
{{- $envoyProxy := $node.envoyProxy | default $.Values.defaults.envoyProxy -}}
{{- $defaults := $.Values.defaults.envoyProxy }}
{{- if $envoyProxy.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy-proxy-{{ $node.name }}
  namespace: {{ default $.Release.Namespace $.Values.global.namespaceOverride }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: envoy-proxy-{{ $node.name }}
  template:
    metadata:
      labels:
        app: envoy-proxy-{{ $node.name }}
        solo.hedera.com/type: envoy-proxy
        {{- include "solo.testLabels" $ | nindent 8 }}
    spec:
        {{- if $.Values.deployment.nodeSelector }}
      nodeSelector:
        {{- $.Values.deployment.nodeSelector | toYaml | nindent 8 }}
        {{- end }}
        {{- if $.Values.deployment.tolerations }}
      tolerations:
        {{- $.Values.deployment.tolerations | toYaml | nindent 8 }}
        {{- end }}
        {{- if $.Values.deployment.affinity }}
      affinity:
        {{- $.Values.deployment.affinity | toYaml | nindent 8 }}
        {{- end }}
        {{- if $.Values.deployment.priorityClassName }}
      priorityClassName: {{ $.Values.deployment.priorityClassName }}
        {{- end }}
      terminationGracePeriodSeconds: {{ $.Values.terminationGracePeriodSeconds }}
      volumes:
        - name: config-volume
          configMap:
            name: envoy-proxy-cm-{{ $node.name }}
        {{- if (lookup "v1" "Secret" (default $.Release.Namespace $.Values.global.namespaceOverride) (printf "envoy-proxy-secret-%s" $node.name)) }}
        - name: tls-volume
          secret:
            secretName: {{ printf "envoy-proxy-secret-%s" $node.name }}
        {{- end }}
      containers:
      - name: {{ default $defaults.nameOverride $envoyProxy.nameOverride }}
        image: {{ include "solo.container.image" (dict "image" $envoyProxy.image "Chart" $.Chart "defaults" $defaults ) }}
        imagePullPolicy: {{ include "solo.images.pullPolicy" (dict "image" $envoyProxy.image "defaults" $defaults) }}
        volumeMounts:
          - name: config-volume
            # https://www.envoyproxy.io/docs/envoy/v1.26.2/start/docker
            mountPath: /etc/envoy
          {{- if (lookup "v1" "Secret" (default $.Release.Namespace $.Values.global.namespaceOverride) (printf "envoy-proxy-secret-%s" $node.name)) }}
          - name: tls-volume
            mountPath: /etc/envoy/tls
            readOnly: true
          {{- end }}
        {{- with default $defaults.resources $envoyProxy.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
{{- end }}
{{- end }}
