{{ range $index, $node := ($.Values.hedera.nodes) }}
{{- $envoyProxy := $node.envoyProxy | default $.Values.defaults.envoyProxy -}}
{{- $defaults := $.Values.defaults.envoyProxy }}
{{- if $envoyProxy.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy-proxy-{{ $node.name }}
  namespace: {{ default $.Release.Namespace $.Values.global.namespaceOverride }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: envoy-proxy-{{ $node.name }}
  template:
    metadata:
      labels:
        app: envoy-proxy-{{ $node.name }}
        solo.hedera.com/type: envoy-proxy
        solo.hedera.com/node-name: {{ $node.name }}
        solo.hedera.com/node-id: "{{ $node.nodeId }}"
        solo.hedera.com/account-id: {{ $node.accountId }}
        {{- include "solo.testLabels" $ | nindent 8 }}
    spec:
      {{- if or $.Values.envoyDeployment.nodeSelector (or $.Values.deployment.nodeSelector $node.nodeSelector) }}
      nodeSelector:
        {{- default $node.nodeSelector (default $.Values.deployment.nodeSelector $.Values.envoyDeployment.nodeSelector) | toYaml | nindent 8 }}
      {{- end }}
      {{- if or $.Values.envoyDeployment.tolerations (or $.Values.deployment.tolerations $node.tolerations) }}
      tolerations:
        {{- default $node.tolerations (default $.Values.deployment.tolerations $.Values.envoyDeployment.tolerations) | toYaml | nindent 8 }}
      {{- end }}
      {{- if or $.Values.envoyDeployment.topologySpreadConstraints (or $.Values.deployment.topologySpreadConstraints $node.topologySpreadConstraints) }}
      topologySpreadConstraints:
        {{- default $node.topologySpreadConstraints (default $.Values.deployment.topologySpreadConstraints $.Values.envoyDeployment.topologySpreadConstraints) | toYaml | nindent 8 }}
      {{- end }}
      {{- if or $.Values.envoyDeployment.affinity (or $.Values.deployment.affinity $node.affinity) }}
      affinity:
        {{- default $node.affinity (default $.Values.deployment.affinity $.Values.envoyDeployment.affinity) | toYaml | nindent 8 }}
      {{- end }}
      {{- if or $.Values.envoyDeployment.priorityClassName (or $.Values.deployment.priorityClassName $node.priorityClassName) }}
      priorityClassName: {{ default $node.priorityClassName (default $.Values.deployment.priorityClassName $.Values.envoyDeployment.priorityClassName) }}
      {{- end }}
      terminationGracePeriodSeconds: {{ $.Values.terminationGracePeriodSeconds }}
      volumes:
        - name: config-volume
          configMap:
            name: envoy-proxy-cm-{{ $node.name }}
        {{- if (lookup "v1" "Secret" (default $.Release.Namespace $.Values.global.namespaceOverride) (printf "envoy-proxy-secret-%s" $node.name)) }}
        - name: tls-volume
          secret:
            secretName: {{ printf "envoy-proxy-secret-%s" $node.name }}
        {{- end }}
      containers:
      - name: {{ default $defaults.nameOverride $envoyProxy.nameOverride }}
        image: {{ include "solo.container.image" (dict "image" $envoyProxy.image "Chart" $.Chart "defaults" $defaults ) }}
        imagePullPolicy: {{ include "solo.images.pullPolicy" (dict "image" $envoyProxy.image "defaults" $defaults) }}
        volumeMounts:
          - name: config-volume
            # https://www.envoyproxy.io/docs/envoy/v1.26.2/start/docker
            mountPath: /etc/envoy
          {{- if (lookup "v1" "Secret" (default $.Release.Namespace $.Values.global.namespaceOverride) (printf "envoy-proxy-secret-%s" $node.name)) }}
          - name: tls-volume
            mountPath: /etc/envoy/tls
            readOnly: true
          {{- end }}
        {{- with default $defaults.resources $envoyProxy.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
{{- end }}
{{- end }}
