{{ range $index, $node := ($.Values.hedera.nodes) }}
{{- $haproxy := $node.haproxy | default $.Values.defaults.haproxy -}}
{{- $defaults := $.Values.defaults.haproxy }}
{{- if $haproxy.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy-{{ $node.name }}
  namespace: {{ default $.Release.Namespace $.Values.global.namespaceOverride }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haproxy-{{ $node.name }}
  template:
    metadata:
      labels:
        app: haproxy-{{ $node.name }}
        solo.hedera.com/type: haproxy
        solo.hedera.com/node-name: {{ $node.name }}
        solo.hedera.com/node-id: "{{ $node.nodeId }}"
        solo.hedera.com/account-id: {{ $node.accountId }}
        {{- include "solo.testLabels" $ | nindent 8 }}
    spec:
      {{- if or $.Values.haproxyDeployment.nodeSelector (or $.Values.deployment.nodeSelector $node.nodeSelector) }}
      nodeSelector:
        {{- default $node.nodeSelector (default $.Values.deployment.nodeSelector $.Values.haproxyDeployment.nodeSelector) | toYaml | nindent 8 }}
      {{- end }}
      {{- if or $.Values.haproxyDeployment.tolerations (or $.Values.deployment.tolerations $node.tolerations) }}
      tolerations:
        {{- default $node.tolerations (default $.Values.deployment.tolerations $.Values.haproxyDeployment.tolerations) | toYaml | nindent 8 }}
      {{- end }}
      {{- if or $.Values.haproxyDeployment.topologySpreadConstraints (or $.Values.deployment.topologySpreadConstraints $node.topologySpreadConstraints) }}
      topologySpreadConstraints:
        {{- default $node.topologySpreadConstraints (default $.Values.deployment.topologySpreadConstraints $.Values.haproxyDeployment.topologySpreadConstraints) | toYaml | nindent 8 }}
      {{- end }}
      {{- if or $.Values.haproxyDeployment.affinity (or $.Values.deployment.affinity $node.affinity) }}
      affinity:
        {{- default $node.affinity (default $.Values.deployment.affinity $.Values.haproxyDeployment.affinity) | toYaml | nindent 8 }}
      {{- end }}
      {{- if or $.Values.haproxyDeployment.priorityClassName (or $.Values.deployment.priorityClassName $node.priorityClassName) }}
      priorityClassName: {{ default $node.priorityClassName (default $.Values.deployment.priorityClassName $.Values.haproxyDeployment.priorityClassName) }}
      {{- end }}
      terminationGracePeriodSeconds: {{ $.Values.terminationGracePeriodSeconds }}
      volumes:
        - name: haproxy-config-volume
          emptyDir: {}
        - name: haproxy-configmap-volume
          configMap:
            name: haproxy-cm-{{ $node.name }}
        - name: haproxy-ofac-volume
          configMap:
            name: haproxy-ofac-cm
      {{- if (lookup "v1" "Secret" (default $.Release.Namespace $.Values.global.namespaceOverride) (printf "haproxy-proxy-secret-%s" $node.name)) }}
        - name: tls-volume
          secret:
            secretName: {{ printf "haproxy-proxy-secret-%s" $node.name }}
      {{- end }}
      containers:
      - name: {{ default $defaults.nameOverride $haproxy.nameOverride }}
        image: {{ include "solo.container.image" (dict "image" $haproxy.image "Chart" $.Chart "defaults" $defaults ) }}
        imagePullPolicy: {{ include "solo.images.pullPolicy" (dict "image" $haproxy.image "defaults" $defaults )  }}
        envFrom:
          - secretRef:
              name: haproxy-secrets
        livenessProbe:
          exec:
            command:
              - "/bin/sh"
              - "-c"
              - |
                rm -f livenessProbe.json || true
                wget -q -O livenessProbe.json --header 'content-type: application/json' http://dataplane:${HAPROXY_PASSWORD}@0.0.0.0:5555/v2/services/haproxy/stats/native?type=backend || return 1
        readinessProbe:
          exec:
            command:
              - "/bin/sh"
              - "-c"
              - |
                rm -f readinessProbe.json || true
                wget -q -O readinessProbe.json --header 'content-type: application/json' http://dataplane:${HAPROXY_PASSWORD}@0.0.0.0:5555/v2/services/haproxy/stats/native?type=backend || return 1
        startupProbe:
          exec:
            command:
            - "/bin/sh"
            - "-c"
            - |
              jq_check() {
                jq --version > /dev/null 2>&1 && return
                echo "jq not found, installing jq"
                apk add jq || return 1
              }
              probe() {
                jq_check || return 1
                wget -q -O response.json --header 'content-type: application/json' http://dataplane:${HAPROXY_PASSWORD}@0.0.0.0:5555/v2/services/haproxy/stats/native?type=backend || return 1
                BACKEND_STATUS=$(jq -r '.[] | .stats[] | select(.name == "http_backend") | .stats.status' < response.json)
                echo "http_backend status: $BACKEND_STATUS"
                if [ "$BACKEND_STATUS" = "UP" ]; then
                  return 0
                else
                  return 1
                fi
              }
              probe
          initialDelaySeconds: 60
          periodSeconds: 5
          failureThreshold: 720
        volumeMounts:
          - name: haproxy-config-volume
            # https://hub.docker.com/_/haproxy/
            mountPath: /usr/local/etc/haproxy
          - name: haproxy-configmap-volume
            # https://hub.docker.com/_/haproxy/
            mountPath: /usr/local/etc/haproxy/haproxy.cfg
            subPath: haproxy.cfg
          - name: haproxy-ofac-volume
            mountPath: /var/opt/
          {{- if (lookup "v1" "Secret" (default $.Release.Namespace $.Values.global.namespaceOverride) (printf "haproxy-proxy-secret-%s" $node.name)) }}
          - name: tls-volume
            mountPath: /usr/local/etc/certs/
            readOnly: true
          {{- end }}
        {{- with default $defaults.resources $haproxy.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
{{- end }}
{{- end }}
