##
# Copyright (C) 2023-2024 Hedera Hashgraph, LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##

name: "ZXC: FS Helm Chart Tests"
# The purpose of this reusable workflow is to compile the code and run the unit tests on every PR and commit.
# This reusable component is called by the following workflows:
# - .github/workflows/flow-pull-request-checks.yaml

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      custom-job-label:
        description: "Custom Job Label:"
        type: string
        required: false
        default: "Helm Chart Test"

defaults:
  run:
    shell: bash

permissions:
  id-token: write
  contents: write
  actions: read
  pull-requests: write
  checks: write
  statuses: write

jobs:
  test:
    name: ${{ inputs.custom-job-label || 'Helm Chart Test' }} (${{ matrix.scriptName }})
    runs-on: solo-linux-medium
    strategy:
      fail-fast: false
      matrix:
        # direct-install.sh uses ubi8-init-java17 image
        # nmt-install.sh uses ubi8-init-dind image
        scriptName: [ direct-install.sh, nmt-install.sh ]
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Install Task
        uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v2.0.0
        with:
          version: 3.39.2
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          # the fetch depth defaults to only the commit that triggered the workflow unless the spotless check was enabled
          fetch-depth: ${{ inputs.enable-spotless-check && '0' || '' }}

      - name: Get changed files related to charts
        id: changed-files
        uses: step-security/changed-files@95b56dadb92a30ca9036f16423fd3c088a71ee94 #v46.0.5
        with:
          files_yaml: |
            chart:
              - charts/**
              - .github/workflows/support/**
            scripts:
              - dev/**

      - name: List all changed files related to charts
        id: check-changed-files
        run: |
          echo "Modified charts files"
          echo "-------------------------------------------------------------------"
          for file in ${{ steps.changed-files.outputs.chart_all_changed_files }}; do
            echo " - ${file} was changed"
          done
          echo ""
          echo "Modified script files"
          echo "-------------------------------------------------------------------"
          for file in ${{ steps.changed-files.outputs.scripts_all_changed_files }}; do
            echo " - ${file} was changed"
          done
          echo ""
          echo " github.event_name = ${{ github.event_name }}"
          if [[ "${{ steps.changed-files.outputs.scripts_any_changed }}" == "true" || "${{ steps.changed-files.outputs.chart_any_changed }}" == "true" ]]; then
            echo "run-tests=true" >> "${GITHUB_OUTPUT}"
            echo "Executing helm chart tests...."
          elif [[ ${{ github.event_name }} == 'workflow_dispatch' ]]; then
            echo "run-tests=true" >> "${GITHUB_OUTPUT}"
            echo "Executing helm chart tests due to workflow dispatch"
          else
            echo ">> No relevant files are changed. No need to run helm chart tests"
          fi

      - name: Initialize Job Variables
        id: vars
        if: ${{ steps.check-changed-files.outputs.run-tests && !cancelled() && !failure() }}
        run: |
          echo "script_name=${{ matrix.scriptName }}" >> "${GITHUB_OUTPUT}"

      - name: Install wget
        run: |
          sudo apt-get update
          sudo apt-get install -y wget

      - name: Setup Kind
        uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0
        if: ${{ steps.check-changed-files.outputs.run-tests && !cancelled() && !failure() }}
        with:
          node_image: kindest/node:v1.27.3@sha256:3966ac761ae0136263ffdb6cfd4db23ef8a83cba8a463690e98317add2c9ba72
          config: .github/workflows/support/dev-cluster.yaml
          version: v0.20.0
          verbosity: 3
          wait: 120s

      - name: Setup Helm
        uses: azure/setup-helm@b9e51907a09c216f16ebe8536097933489208112 # v4.3.0
        if: ${{ steps.check-changed-files.outputs.run-tests && !cancelled() && !failure() }}
        with:
          version: "v3.12.3" #  helm version

      # Technically, this step is not required for the unit tests to run, but it is useful for debugging setup issues.
      - name: Kubernetes Cluster Info
        if: ${{ steps.check-changed-files.outputs.run-tests && !cancelled() && !failure() }}
        run: |
          kubectl config get-contexts
          kubectl get crd
          kubectl get node --show-labels

      - name: Helm Chart Test
        working-directory: .github/workflows/support
        if: ${{ steps.check-changed-files.outputs.run-tests && !cancelled() && !failure() }}
        run: |
          task test-"${{ steps.vars.outputs.script_name}}"
